### PR TITLE
Make generic over a Field trait

### PR DESCRIPTION
**Pull request by rphmeier**
And implement it for `galois_8`. 
After #38 I will add an implementation for `galois_16` as well.

### CODE REVIEW

**Comment by rphmeier** [comment]
I'd be interested to see if there is a performance hit for GF(2^8) with the generification.

**Comment by darrenldl** [comment]
I can try benchmarking it later.

If there is a significant performance hit, what would be your suggestion though?

**Comment by darrenldl** [comment]
Sorry haven't quite gotten to setting up benchmarking due to time constraint, but I went through the changes and it should be fine, as `galois_8::Field` implementation of `mul_slice` and `mul_slice_xor` are using the lower level ones rather than the higher level default one in `lib.rs`.

Majority of the time is spent in coding, specifically `mul_slice`, so even if other parts carry slight overhead, it shouldn't impact encoding phase too much, if noticeable at all.

`Matrix` is pretty simple to begin with, and matrix generation occupies relatively small portion of the execution time in general due to `InversionTree` caching matrices. So unless the generification causes `InversionTree` to cache a lot slower for some reason, overall the performance should be almost the same as before.

**Comment by darrenldl** [comment]
Huh, so rayon did speed things up a lot.

Do you have the specific numbers?

**Comment by darrenldl** [comment]
Okay yeah, that makes a lot of sense now that I think about it, independent slice coding do allow speed up linear to (parity) shard count.

But yeah, the generification itself seems fine. If we really want, we can benchmark with rayon set to using single thread, then it should show the overhead of generifcation, if any exists at all. But I personally don't feel this is too useful.

**Comment by rphmeier** [comment]
(I was accidentally benchmarking w/o simd acceleration due to the feature change)

Old without rayon:
```
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 1024
    time taken       : 0.745146417
    byte count       : 5242880000
    MB/s             : 6710.090642494494
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 4096
    time taken       : 0.746232383
    byte count       : 5242880000
    MB/s             : 6700.325681256317
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 8192
    time taken       : 0.794534702
    byte count       : 5242880000
    MB/s             : 6292.991341239114
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 16384
    time taken       : 0.762313775
    byte count       : 5242880000
    MB/s             : 6558.978945382431
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 32768
    time taken       : 0.883574129
    byte count       : 5242880000
    MB/s             : 5658.834766539436
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 65536
    time taken       : 0.784516589
    byte count       : 5242880000
    MB/s             : 6373.351526413676
```

New with `simd-accel`:
```
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 1024
    time taken       : 0.814699297
    byte count       : 5242880000
    MB/s             : 6137.233723426179
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 4096
    time taken       : 0.829256454
    byte count       : 5242880000
    MB/s             : 6029.497842171753
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 8192
    time taken       : 0.736849525
    byte count       : 5242880000
    MB/s             : 6785.645956682947
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 16384
    time taken       : 0.733428098
    byte count       : 5242880000
    MB/s             : 6817.30085557753
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 32768
    time taken       : 0.740080925
    byte count       : 5242880000
    MB/s             : 6756.017931417433
encode :
    shards           : 10 / 2
    shard length     : 1048576
    bytes per encode : 65536
    time taken       : 0.744777619
    byte count       : 5242880000
    MB/s             : 6713.413336337112
```

**Comment by rphmeier** [comment]
(in short, seems about the same.)

**Comment by darrenldl** [comment]
Sounds about right - 2 parity shards are used in the benchmarks.

So I think this PR looks good, as nothing important is changed. I'm not sure if there's a very good way to test the `impl crate::Field for Field { ... }` part to make sure the right actual functions are used for the `impl` other than duplicating all the existing tests, so I'll just open an issue and see if any new idea pops up.

I'll merge this if you think it's okay.

**Comment by rphmeier** [comment]
yes please :)

**Pull request merged**
