### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by rphmeier**
Changes:
  - Got rid of other projects' sources in the repo
  - Removed unused galois functions (in preparation for making this more generic)
  - Removed the `shards` types and all functions referencing it in favor of a generic API that accommodates direct slices and boxed-slices. This reduces the audit and API surface substantially
  - Altered SIMD acceleration to be present under `simd-accel` feature to avoid libc linkage when unnecessary (this should make it viable for no-std, assuming rayon can be made optional)
  - Removed `Rayon` in a couple places because it requires a `Send` bound on some of the generic types

### CODE REVIEW

**Comment by darrenldl** [comment]
I think the following lines might be missing in `lib.rs`

```
mod matrix_tests;
mod inversion_tree_tests;
```

as the tests under those files seem to be missing from the running tests list.

**Comment by rphmeier** [comment]
W.r.t. Adding back the SIMD, I would recommend doing this under a `simd-accel` feature as opposed to disabling it with `pure-rust` -- this is because features are supposed to be additive and SIMD acceleration adds dependencies in the build script and at link time.

**Comment by darrenldl** [comment]
Sounds good.

Feel free to bump the version number to `4.0.0` and update CHANGELOG.md in this PR.

I can do those later on as well if you feel like doing them in a separate PR

I'll inform some of the major users later on when `4.0.0` is published.

**Comment by rphmeier** [comment]
@darrenldl Will do -- I'll update the README, CHANGELOG, and major version. Maybe we should hold off on publishing until some generification changes are in. But I'd prefer to do that in a follow-on PR since it will contain major logic changes

**Comment by darrenldl** [comment]
Oh yep certainly, not going to rush the publishing - just simply feel like mentioning/doing admin tasks while I remember.

Just to make sure we're on the same page, my understanding is that we will wait until the actual work for `GF(2^16)` or `GF(2^32)` is done and the API is finalised before publishing. Would that be correct?

**Comment by rphmeier** [comment]
Yes, I think that would be the right approach

**Comment by darrenldl** [comment]
> I'm not sure how the coverage for matrix.rs, errors.rs, and inversion_tree.rs could have dropped -- i haven't made any significant changes in those files

Don't worry about the coverage too much - right now it uses kcov, which doesn't account for Rust code very accurately, and code coverage in general is relatively noisy anyway. There might be other tools for more accurate Rust code coverage, but I haven't kept track with the trend of code coverage tools at all lately.

We can investigate this in another PR if there are new tools which vastly improve accuracy, but I don't feel it's very necessary.

I'll go through the reports after it's merged (reports don't seem to work properly in PRs) to see if anything's actually missing, but as long as it's 9X%, I'm not too worried really.

> There are also some rayon changes here, and I might want to revisit parallelism somehow for 4.0.0 to make it more no-std suitable.

I can't remember if rayon provided significant speed up actually, I added them when I was playing catch up with the Go version of the library (`go` construct was used in encoding non-overlapping slices concurrently). Some use of rayon was to mimic that parallelism.

Feel free to remove the use of rayon as you deem necessary in this PR, we can do some benchmarks afterwards to see if it's desirable to add them back. Adding rayon back shouldn't be too difficult anyway.

**Comment by rphmeier** [comment]
Rayon might be better employed externally than internally. We could remove `rayon` for now and reintroduce as a wrapper for `ReedSolomon` that handles the `parallel_param` and fork/joins large shards.

**Comment by darrenldl** [comment]
> Rayon might be better employed externally than internally. We could remove rayon for now and reintroduce as a wrapper for ReedSolomon that handles the parallel_param and fork/joins large shards.

Benchmark will need to be done to see if this would still be useful at all after removal of internal concurrent slice encoding. I very vaguely recall slice splitting (which is what `parallel_param` is for) is less helpful than concurrent slice encoding, but lets investigate that in another PR. Feel free to remove `rayon` entirely for now.

---

Just FYI, though you're probably aware of already, AppVeyor doesn't move onto testing the new commits until the current batch is done, while Travis-CI always jumps to the newest commit, so just ignore AppVeyor and use Travis-CI if you're looking for the newest test results.

**Comment by rphmeier** [comment]
I think that's all the changes I'd like to make in this PR. Thanks for the review and feedback so far!

**Comment by darrenldl** [comment]
I just went through the diffs of test outputs of several commits in the PR to make sure the disappearing tests are indeed no longer needed, and that does seem to be the case.

Thanks very much again for your work on this PR, I'll merge the PR once AppVeyor finishes.

**Pull request merged**
